apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-printer
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      containers:
      - name: date-printer
        image: sanderjenk/echo-job:1.1
      restartPolicy: Never