apiVersion: batch/v1
kind: Job
metadata:
  name: date-printer
spec:
  template:
    spec:
      containers:
      - name: date-printer
        image: sanderjenk/echo-job:1.1
      restartPolicy: Never
  backoffLimit: 4