apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: sanderjenk/static-website:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-website
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: static-website
  sessionAffinity: None
  type: LoadBalancer